name: Atualizar lista de repositórios

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite execução manual

jobs:
  update-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Buscar repositórios e atualizar README
        run: |
          # Busca repositórios via API do GitHub
          REPOS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/users/soujoaomoraes/repos?sort=updated&per_page=10" | \
            jq -r '.[] | select(.fork == false) | "- [\(.name)](\(.html_url)) - \(.description // "Sem descrição")"' | \
            head -5)
          
          # Cria o novo conteúdo do README
          cat > README.md << 'EOF'
          **👋 Sobre mim**
          
          Olá! Sou um desenvolvedor apaixonado por tecnologia, inovação e aprendizado constante. Gosto de explorar novas ferramentas, automatizar processos e criar soluções úteis no dia a dia.
          
          **🚀 Repositórios**
          
          *Lista atualizada automaticamente via GitHub Actions*
          
          EOF
          
          # Adiciona a lista de repositórios
          echo "$REPOS" >> README.md
          
          # Adiciona timestamp
          echo "" >> README.md
          echo "*Última atualização: $(date -u '+%d/%m/%Y às %H:%M UTC')*" >> README.md
          
      - name: Commit e push se houver mudanças
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          
          # Verifica se há mudanças para commitar
          if git diff --staged --quiet; then
            echo "Nenhuma mudança detectada"
          else
            git commit -m "✨ Atualiza lista de repositórios automaticamente"
            git push
            echo "README atualizado com sucesso!"
          fi
