name: Atualizar lista de repositórios

on:
  schedule:
    - cron: "0 0 * * *"  # Corrigido: era "0 0 * **", agora é "0 0 * * *"
  push:
    branches: [ main ]  # Adicionado: especifica a branch
  workflow_dispatch:  # Permite execução manual para testes

jobs:
  update-repos:
    runs-on: ubuntu-latest
    permissions:  # Adicionado: permissions necessárias
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Atualizar lista de repositórios
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          query: "user:soujoaomoraes"
          max: 5
          
      - name: Commit e push se houver mudanças
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --staged --quiet || (git commit -m "✨ Atualiza lista de repositórios" && git push)
